/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e4e2e2",
        "on-error": "#ffffff",
        "primary-fixed": "#ffdcc4",
        "on-secondary": "#ffffff",
        "on-primary-container": "#fffbff",
        "on-tertiary-fixed": "#1c1c1a",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#474745",
        "surface-container-high": "#e9e8e7",
        "inverse-primary": "#f0bc97",
        "tertiary-container": "#757472",
        "tertiary": "#5d5c5a",
        "tertiary-fixed-dim": "#c8c6c3",
        "on-secondary-fixed": "#1c1b1b",
        "primary-container": "#966b4b",
        "surface-dim": "#dbdad9",
        "outline": "#82746b",
        "on-primary-fixed": "#2f1400",
        "surface": "#fbf9f9",
        "secondary-fixed": "#e5e2e1",
        "on-primary": "#ffffff",
        "on-background": "#1b1c1c",
        "surface-container-low": "#f5f3f3",
        "tertiary-fixed": "#e5e2df",
        "outline-variant": "#d5c3b9",
        "on-surface": "#1b1c1c",
        "on-surface-variant": "#50443d",
        "on-primary-fixed-variant": "#623e22",
        "background": "#fbf9f9",
        "on-secondary-fixed-variant": "#474746",
        "inverse-on-surface": "#f2f0f0",
        "error": "#ba1a1a",
        "secondary-container": "#e2dfde",
        "inverse-surface": "#303031",
        "secondary": "#5f5e5e",
        "surface-container": "#efeded",
        "surface-bright": "#fbf9f9",
        "primary": "#7b5335",
        "on-secondary-container": "#636262",
        "on-tertiary-container": "#f9ffec",
        "surface-tint": "#7d5637",
        "primary-fixed-dim": "#f0bc97",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e4e2e2",
        "secondary-fixed-dim": "#c8c6c5"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "120px",
        "stack-md": "16px",
        "margin-mobile": "20px",
        "stack-sm": "8px",
        "gutter": "24px",
        "stack-lg": "32px",
        "margin-desktop": "64px",
        "container-max": "1280px"
      },
      fontFamily: {
        "display-lg-mobile": ["Libre Caslon Text", "serif"],
        "button": ["Work Sans", "sans-serif"],
        "body-md": ["Work Sans", "sans-serif"],
        "label-caps": ["Work Sans", "sans-serif"],
        "headline-md": ["Libre Caslon Text", "serif"],
        "display-lg": ["Libre Caslon Text", "serif"],
        "body-lg": ["Work Sans", "sans-serif"],
        "headline-sm": ["Libre Caslon Text", "serif"]
      },
      fontSize: {
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "400" }],
        "button": ["14px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.15em", fontWeight: "600" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
